### ISSUE TITLE
[Top Priority] Open source Makeen

### ISSUE THREAD

**Issue by Ameerplus** [viczam/makeen-hapi#44]
Please review
http://www.gnu.org/licenses/agpl-3.0.html

And comment in the #general slack channel if you have objections to using this license to open source Makeen.

**Comment by nicolasembleton** [comment]
Hi guys. What is this about? Making it officially open source and planning for the communication strategy?

**Comment by neekz0r** [comment]
@nicolasembleton  More or less, yes. I've updated the comment to reflect where to look and what to do.

**Comment by nicolasembleton** [comment]
Thanks @neekz0r. 
Discussion on Slack: First chain of thought is that GPL is a very limiting license hence pretty painful for everyone. MIT has always had my preference despite being very permissive.
Checking other frameworks with the same `goal` and `business model` in mind, they’re all `MIT`
 ```The Sails framework is free and open-source under the MIT License.
https://github.com/zurb/foundation-apps/blob/master/LICENSE
https://github.com/zurb/foundation-sites/blob/develop/LICENSE
https://github.com/strongloop/loopback/blob/master/LICENSE
```
So that would likely confirm my assumptions that focusing on the service and allowing full freedom for development is likely the way to go.
The single most important detail is `what` is being open-sourced and my take is that the `core` should absolutely be an MIT to allow for maximum community involvement. Some plugins too, but separately.

**Comment by viczam** [comment]
Done. We went with MIT, so I guess I can close this issue.
